// Generated by Bisonc++ V2.09.03 on Sat, 22 Mar 2014 16:06:08 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {286, 3}, // 1: program ->  optional_declaration_list procedure_name procedure_body
     {287, 0}, // 2: optional_declaration_list ->  <empty>
     {287, 1}, // 3: optional_declaration_list ->  declaration_statement_list
     {288, 3}, // 4: procedure_name (NAME) ->  NAME '(' ')'
     {289, 5}, // 5: procedure_body ('{') ->  '{' declaration_statement_list #0001 basic_block_list '}'
     {290, 0}, // 6: #0001 ->  <empty>
     {289, 3}, // 7: procedure_body ('{') ->  '{' basic_block_list '}'
     {291, 1}, // 8: declaration_statement_list ->  declaration_statement
     {291, 2}, // 9: declaration_statement_list ->  declaration_statement_list declaration_statement
     {292, 3}, // 10: declaration_statement (INTEGER) ->  INTEGER NAME ';'
     {293, 2}, // 11: basic_block_list ->  basic_block_list basic_block
     {293, 1}, // 12: basic_block_list ->  basic_block
     {294, 3}, // 13: basic_block (BBNUM) ->  BBNUM ':' executable_statement_list
     {295, 1}, // 14: executable_statement_list ->  assignment_statement_list
     {295, 3}, // 15: executable_statement_list (RETURN) ->  assignment_statement_list RETURN ';'
     {295, 2}, // 16: executable_statement_list ->  assignment_statement_list if_else_statement
     {295, 2}, // 17: executable_statement_list ->  assignment_statement_list goto_statement
     {296, 0}, // 18: assignment_statement_list ->  <empty>
     {296, 2}, // 19: assignment_statement_list ->  assignment_statement_list assignment_statement
     {297, 4}, // 20: assignment_statement (ASSIGN_OP) ->  variable ASSIGN_OP expression ';'
     {298, 7}, // 21: if_else_statement (IF) ->  IF '(' relational_expression ')' goto_statement ELSE goto_statement
     {299, 3}, // 22: goto_statement (GOTO) ->  GOTO BBNUM ';'
     {300, 3}, // 23: relational_expression (eq) ->  expression eq expression
     {300, 3}, // 24: relational_expression (ne) ->  expression ne expression
     {300, 3}, // 25: relational_expression (le) ->  expression le expression
     {300, 3}, // 26: relational_expression (ge) ->  expression ge expression
     {300, 3}, // 27: relational_expression (lt) ->  expression lt expression
     {300, 3}, // 28: relational_expression (gt) ->  expression gt expression
     {301, 1}, // 29: expression ->  variable_or_constant
     {301, 1}, // 30: expression ->  relational_expression
     {301, 3}, // 31: expression ('(') ->  '(' relational_expression ')'
     {302, 1}, // 32: variable_or_constant ->  variable
     {302, 1}, // 33: variable_or_constant ->  constant
     {303, 1}, // 34: variable (NAME) ->  NAME
     {304, 1}, // 35: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {305, 1}, // 36: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_DEF}, {  6} },                              
    { {     286}, {  1} }, // program                   
    { {     287}, {  2} }, // optional_declaration_list 
    { {     291}, {  3} }, // declaration_statement_list
    { {     292}, {  4} }, // declaration_statement     
    { {     261}, {  5} }, // INTEGER                   
    { {       0}, { -2} },                              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 3} },                  
    { {       288}, { 6} }, // procedure_name
    { {       259}, { 7} }, // NAME          
    { {         0}, { 0} },                  
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  3} },                         
    { {     292}, {  8} }, // declaration_statement
    { {     261}, {  5} }, // INTEGER              
    { {       0}, { -3} },                         
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, { 2} },        
    { {       259}, { 9} }, // NAME
    { {         0}, { 0} },        
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       289}, { 10} }, // procedure_body
    { {       123}, { 11} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 12} }, // '('
    { {         0}, {  0} },       
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 13} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  7} },                              
    { {       291}, { 14} }, // declaration_statement_list
    { {       293}, { 15} }, // basic_block_list          
    { {       292}, {  4} }, // declaration_statement     
    { {       294}, { 16} }, // basic_block               
    { {       261}, {  5} }, // INTEGER                   
    { {       258}, { 17} }, // BBNUM                     
    { {         0}, {  0} },                              
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 18} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_14[] =
{
    { { REQ_DEF}, {  4} },                         
    { {     290}, { 19} }, // #0001                
    { {     292}, {  8} }, // declaration_statement
    { {     261}, {  5} }, // INTEGER              
    { {       0}, { -6} },                         
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 20} }, // '}'        
    { {       294}, { 21} }, // basic_block
    { {       258}, { 17} }, // BBNUM      
    { {         0}, {  0} },               
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 22} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_18[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       293}, { 23} }, // basic_block_list
    { {       294}, { 16} }, // basic_block     
    { {       258}, { 17} }, // BBNUM           
    { {         0}, {  0} },                    
};

SR__ s_20[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   3} },                             
    { {     295}, {  24} }, // executable_statement_list
    { {     296}, {  25} }, // assignment_statement_list
    { {       0}, { -18} },                             
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 26} }, // '}'        
    { {       294}, { 21} }, // basic_block
    { {       258}, { 17} }, // BBNUM      
    { {         0}, {  0} },               
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_25[] =
{
    { { REQ_DEF}, {   9} },                        
    { {     260}, {  27} }, // RETURN              
    { {     298}, {  28} }, // if_else_statement   
    { {     299}, {  29} }, // goto_statement      
    { {     297}, {  30} }, // assignment_statement
    { {     262}, {  31} }, // IF                  
    { {     264}, {  32} }, // GOTO                
    { {     303}, {  33} }, // variable            
    { {     259}, {  34} }, // NAME                
    { {       0}, { -14} },                        
};

SR__ s_26[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 35} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 36} }, // '('
    { {         0}, {  0} },       
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       258}, { 37} }, // BBNUM
    { {         0}, {  0} },         
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       265}, { 38} }, // ASSIGN_OP
    { {         0}, {  0} },             
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       300}, { 39} }, // relational_expression
    { {       301}, { 40} }, // expression           
    { {       302}, { 41} }, // variable_or_constant 
    { {        40}, { 42} }, // '('                  
    { {       303}, { 43} }, // variable             
    { {       304}, { 44} }, // constant             
    { {       259}, { 34} }, // NAME                 
    { {       257}, { 45} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 46} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       301}, { 47} }, // expression           
    { {       302}, { 41} }, // variable_or_constant 
    { {       300}, { 48} }, // relational_expression
    { {        40}, { 42} }, // '('                  
    { {       303}, { 43} }, // variable             
    { {       304}, { 44} }, // constant             
    { {       259}, { 34} }, // NAME                 
    { {       257}, { 45} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_39[] =
{
    { { REQ_DEF}, {   2} },       
    { {      41}, {  49} }, // ')'
    { {       0}, { -30} },       
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  7} },      
    { {       267}, { 50} }, // eq
    { {       266}, { 51} }, // ne
    { {       269}, { 52} }, // le
    { {       271}, { 53} }, // ge
    { {       268}, { 54} }, // lt
    { {       270}, { 55} }, // gt
    { {         0}, {  0} },      
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       300}, { 56} }, // relational_expression
    { {       301}, { 40} }, // expression           
    { {       302}, { 41} }, // variable_or_constant 
    { {        40}, { 42} }, // '('                  
    { {       303}, { 43} }, // variable             
    { {       304}, { 44} }, // constant             
    { {       259}, { 34} }, // NAME                 
    { {       257}, { 45} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  8} },       
    { {        59}, { 57} }, // ';'
    { {       267}, { 50} }, // eq 
    { {       266}, { 51} }, // ne 
    { {       269}, { 52} }, // le 
    { {       271}, { 53} }, // ge 
    { {       268}, { 54} }, // lt 
    { {       270}, { 55} }, // gt 
    { {         0}, {  0} },       
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       299}, { 58} }, // goto_statement
    { {       264}, { 32} }, // GOTO          
    { {         0}, {  0} },                  
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       301}, { 59} }, // expression           
    { {       302}, { 41} }, // variable_or_constant 
    { {       300}, { 48} }, // relational_expression
    { {        40}, { 42} }, // '('                  
    { {       303}, { 43} }, // variable             
    { {       304}, { 44} }, // constant             
    { {       259}, { 34} }, // NAME                 
    { {       257}, { 45} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       301}, { 60} }, // expression           
    { {       302}, { 41} }, // variable_or_constant 
    { {       300}, { 48} }, // relational_expression
    { {        40}, { 42} }, // '('                  
    { {       303}, { 43} }, // variable             
    { {       304}, { 44} }, // constant             
    { {       259}, { 34} }, // NAME                 
    { {       257}, { 45} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       301}, { 61} }, // expression           
    { {       302}, { 41} }, // variable_or_constant 
    { {       300}, { 48} }, // relational_expression
    { {        40}, { 42} }, // '('                  
    { {       303}, { 43} }, // variable             
    { {       304}, { 44} }, // constant             
    { {       259}, { 34} }, // NAME                 
    { {       257}, { 45} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       301}, { 62} }, // expression           
    { {       302}, { 41} }, // variable_or_constant 
    { {       300}, { 48} }, // relational_expression
    { {        40}, { 42} }, // '('                  
    { {       303}, { 43} }, // variable             
    { {       304}, { 44} }, // constant             
    { {       259}, { 34} }, // NAME                 
    { {       257}, { 45} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       301}, { 63} }, // expression           
    { {       302}, { 41} }, // variable_or_constant 
    { {       300}, { 48} }, // relational_expression
    { {        40}, { 42} }, // '('                  
    { {       303}, { 43} }, // variable             
    { {       304}, { 44} }, // constant             
    { {       259}, { 34} }, // NAME                 
    { {       257}, { 45} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       301}, { 64} }, // expression           
    { {       302}, { 41} }, // variable_or_constant 
    { {       300}, { 48} }, // relational_expression
    { {        40}, { 42} }, // '('                  
    { {       303}, { 43} }, // variable             
    { {       304}, { 44} }, // constant             
    { {       259}, { 34} }, // NAME                 
    { {       257}, { 45} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_56[] =
{
    { { REQ_DEF}, {   2} },       
    { {      41}, {  65} }, // ')'
    { {       0}, { -30} },       
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       263}, { 66} }, // ELSE
    { {         0}, {  0} },        
};

SR__ s_59[] =
{
    { { REQ_DEF}, {   5} },      
    { {     269}, {  52} }, // le
    { {     271}, {  53} }, // ge
    { {     268}, {  54} }, // lt
    { {     270}, {  55} }, // gt
    { {       0}, { -23} },      
};

SR__ s_60[] =
{
    { { REQ_DEF}, {   5} },      
    { {     269}, {  52} }, // le
    { {     271}, {  53} }, // ge
    { {     268}, {  54} }, // lt
    { {     270}, {  55} }, // gt
    { {       0}, { -24} },      
};

SR__ s_61[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_63[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       299}, { 67} }, // goto_statement
    { {       264}, { 32} }, // GOTO          
    { {         0}, {  0} },                  
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         program_object.set_procedure_map(current_procedure, get_line_number());
         program_object.global_list_in_proc_map_check();
         }
         }
        break;

        case 2:
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = new Symbol_Table();
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 3:
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[0].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 4:
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-2].string_value != NULL), "Procedure name cannot be null");
         string proc_name = *d_vsp__[-2].string_value;
         current_procedure = new Procedure(void_data_type, proc_name, get_line_number());
         }
         }
        break;

        case 5:
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         CHECK_INVARIANT((d_vsp__[-1].basic_block_list != NULL), "Basic block list cannot be null");
         current_procedure->set_basic_block_list(*d_vsp__[-1].basic_block_list);
         }
         }
        break;

        case 6:
        d_val__ = d_vsp__[-1];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         Symbol_Table * local_table = d_vsp__[0].symbol_table;
         if (local_table == NULL)
         local_table = new Symbol_Table();
         current_procedure->set_local_list(*local_table);
         }
         }
        break;

        case 7:
        {
         if (NOT_ONLY_PARSE)
         {
         list<Basic_Block *> * bb_list = d_vsp__[-1].basic_block_list;
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         CHECK_INVARIANT((bb_list != NULL), "Basic block list cannot be null");
         current_procedure->set_basic_block_list(*bb_list);
         }
         }
        break;

        case 8:
        {
         if (NOT_ONLY_PARSE)
         {
         int line = get_line_number();
         program_object.variable_in_proc_map_check(d_vsp__[0].symbol_entry->get_variable_name());
         string var_name = d_vsp__[0].symbol_entry->get_variable_name();
         if (current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != var_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         }
         }
        break;

        case 9:
        {
         if (NOT_ONLY_PARSE)
         {
         
         
         int line = get_line_number();
         program_object.variable_in_proc_map_check(d_vsp__[0].symbol_entry->get_variable_name());
         string var_name = d_vsp__[0].symbol_entry->get_variable_name();
         if (current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != var_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         if (d_vsp__[-1].symbol_table != NULL)
         {
         CHECK_INPUT((d_vsp__[-1].symbol_table->variable_in_symbol_list_check(var_name) == false),
         "Variable is declared twice", get_line_number());
         d_val__.symbol_table = d_vsp__[-1].symbol_table;
         }
         else
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         }
         }
        break;

        case 10:
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-1].string_value != NULL), "Name cannot be null");
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[-1].string_value, int_data_type, get_line_number());
         }
         }
        break;

        case 11:
        {
         if (NOT_ONLY_PARSE)
         {
         list<Basic_Block *> * bb_list = d_vsp__[-1].basic_block_list;
         Basic_Block * bb = d_vsp__[0].basic_block;
         CHECK_INVARIANT((bb_list != NULL), "New basic block cannot be null");
         CHECK_INVARIANT((bb != NULL), "Basic block cannot be null");
         bb_strictly_increasing_order_check(bb_list, bb->get_bb_number());
         bb_list->push_back(d_vsp__[0].basic_block);
         d_val__.basic_block_list = bb_list;
         }
         }
        break;

        case 12:
        {
         if (NOT_ONLY_PARSE)
         {
         Basic_Block * bb = d_vsp__[0].basic_block;
         CHECK_INVARIANT((bb != NULL), "Basic block cannot be null");
         list<Basic_Block *> * bb_list = new list<Basic_Block *>;
         bb_list->push_back(bb);
         d_val__.basic_block_list = bb_list;
         }
         }
        break;

        case 13:
        {
         if (NOT_ONLY_PARSE)
         {
         int bb_number = d_vsp__[-2].integer_value;
         list<Ast *> * exe_stmt = d_vsp__[0].ast_list;
         CHECK_INPUT((bb_number >= 2), "Illegal basic block lable", get_line_number());
         Basic_Block * bb = new Basic_Block(bb_number, get_line_number());
         if (exe_stmt != NULL)
         bb->set_ast_list(*exe_stmt);
         else
         {
         list<Ast *> * ast_list = new list<Ast *>;
         bb->set_ast_list(*ast_list);
         }
         d_val__.basic_block = bb;
         }
         }
        break;

        case 14:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast_list = d_vsp__[0].ast_list;
         }
         }
        break;

        case 15:
        {
         if (NOT_ONLY_PARSE)
         {
         list<Ast *> * assign_list = d_vsp__[-2].ast_list;
         Ast * ret = new Return_Ast(get_line_number());
         list<Ast *> * exe_list = NULL;
         if (assign_list)
         exe_list = assign_list;
         else
         exe_list = new list<Ast *>;
         exe_list->push_back(ret);
         d_val__.ast_list = exe_list;
         }
         }
        break;

        case 16:
        {
         if(NOT_ONLY_PARSE)
         {
         if (d_vsp__[-1].ast_list != NULL)
         d_val__.ast_list = d_vsp__[-1].ast_list;
         else
         d_val__.ast_list = new list<Ast *>;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         }
         }
        break;

        case 17:
        {
         if(NOT_ONLY_PARSE)
         {
         if (d_vsp__[-1].ast_list != NULL)
         d_val__.ast_list = d_vsp__[-1].ast_list;
         else
         d_val__.ast_list = new list<Ast *>;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         }
         }
        break;

        case 18:
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast_list = NULL;
         }
         }
        break;

        case 19:
        {
         if(NOT_ONLY_PARSE)
         {
         Ast * assign_stmt = d_vsp__[0].ast;
         CHECK_INVARIANT((assign_stmt != NULL), "Assignment statement cannot be null");
         if (d_vsp__[-1].ast_list == NULL)
         d_val__.ast_list = new list<Ast *>;
         else
         d_val__.ast_list = d_vsp__[-1].ast_list;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         }
         }
        break;

        case 20:
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-3].ast != NULL) && (d_vsp__[-1].ast != NULL)), "lhs/rhs cannot be null");
         d_val__.ast = new Assignment_Ast(d_vsp__[-3].ast, d_vsp__[-1].ast, get_line_number());
         d_val__.ast->check_ast();
         }
         }
        break;

        case 21:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = new If_Else_Ast(d_vsp__[-2].ast, d_vsp__[-4].ast, d_vsp__[0].ast, get_line_number());
         d_val__.ast->check_ast();
         }
         }
        break;

        case 22:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = new Goto_Ast(d_vsp__[-1].integer_value, get_line_number());
         d_val__.ast->check_ast();
         }
         }
        break;

        case 23:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, EQ, d_vsp__[0].ast, get_line_number());
         }
         }
        break;

        case 24:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, NE, d_vsp__[0].ast, get_line_number());
         }
         }
        break;

        case 25:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, LE, d_vsp__[0].ast, get_line_number());
         }
         }
        break;

        case 26:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, GE, d_vsp__[0].ast, get_line_number());
         }
         }
        break;

        case 27:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, LT, d_vsp__[0].ast, get_line_number());
         }
         }
        break;

        case 28:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, GT, d_vsp__[0].ast, get_line_number());
         }
         }
        break;

        case 29:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 30:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 31:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[-1].ast;
         }
         }
        break;

        case 32:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 33:
        {
         if(NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 34:
        {
         if(NOT_ONLY_PARSE)
         {
         Symbol_Table_Entry * var_table_entry;
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Variable name cannot be null");
         string var_name = *d_vsp__[0].string_value;
         if (current_procedure->variable_in_symbol_list_check(var_name) == true)
         var_table_entry = &(current_procedure->get_symbol_table_entry(var_name));
         else if (program_object.variable_in_symbol_list_check(var_name) == true)
         var_table_entry = &(program_object.get_symbol_table_entry(var_name));
         else
         CHECK_INVARIANT(CONTROL_SHOULD_NOT_REACH, "Variable has not been declared");
         Ast * name_ast = new Name_Ast(var_name, *var_table_entry, get_line_number());
         d_val__.ast = name_ast;
         }
         }
        break;

        case 35:
        {
         if (NOT_ONLY_PARSE)
         {
         int num = d_vsp__[0].integer_value;
         Ast * num_ast = new Number_Ast<int>(num, int_data_type, get_line_number());
         d_val__.ast = num_ast;
         }
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

