// Generated by Bisonc++ V2.09.03 on Sat, 01 Mar 2014 23:46:00 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {283, 2}, // 1: program ->  global_declaration_statement_list procedure_list
     {283, 1}, // 2: program ->  procedure_list
     {285, 4}, // 3: procedure_list ->  procedure_list procedure_name #0001 procedure_body
     {288, 0}, // 4: #0001 ->  <empty>
     {285, 3}, // 5: procedure_list ->  procedure_name #0002 procedure_body
     {289, 0}, // 6: #0002 ->  <empty>
     {286, 4}, // 7: procedure_name (NAME) ->  NAME '(' argument_list ')'
     {286, 3}, // 8: procedure_name (NAME) ->  NAME '(' ')'
     {287, 5}, // 9: procedure_body ('{') ->  '{' declaration_statement_list #0003 basic_block_list '}'
     {293, 0}, // 10: #0003 ->  <empty>
     {287, 3}, // 11: procedure_body ('{') ->  '{' basic_block_list '}'
     {284, 1}, // 12: global_declaration_statement_list ->  gloabal_declaration_statement
     {284, 2}, // 13: global_declaration_statement_list ->  global_declaration_statement_list gloabal_declaration_statement
     {294, 1}, // 14: gloabal_declaration_statement ->  declaration_statement
     {294, 1}, // 15: gloabal_declaration_statement ->  function_declaration_statement
     {295, 3}, // 16: declaration_statement (INTEGER) ->  INTEGER NAME ';'
     {295, 3}, // 17: declaration_statement (FLOAT) ->  FLOAT NAME ';'
     {295, 3}, // 18: declaration_statement (DOUBLE) ->  DOUBLE NAME ';'
     {296, 6}, // 19: function_declaration_statement (INTEGER) ->  INTEGER NAME '(' argument_list ')' ';'
     {296, 6}, // 20: function_declaration_statement (FLOAT) ->  FLOAT NAME '(' argument_list ')' ';'
     {296, 6}, // 21: function_declaration_statement (DOUBLE) ->  DOUBLE NAME '(' argument_list ')' ';'
     {296, 6}, // 22: function_declaration_statement (VOID) ->  VOID NAME '(' argument_list ')' ';'
     {296, 5}, // 23: function_declaration_statement (INTEGER) ->  INTEGER NAME '(' ')' ';'
     {296, 5}, // 24: function_declaration_statement (FLOAT) ->  FLOAT NAME '(' ')' ';'
     {296, 5}, // 25: function_declaration_statement (DOUBLE) ->  DOUBLE NAME '(' ')' ';'
     {296, 5}, // 26: function_declaration_statement (VOID) ->  VOID NAME '(' ')' ';'
     {290, 3}, // 27: argument_list (',') ->  argument_list ',' argument
     {290, 1}, // 28: argument_list ->  argument
     {297, 2}, // 29: argument (INTEGER) ->  INTEGER NAME
     {297, 2}, // 30: argument (FLOAT) ->  FLOAT NAME
     {297, 2}, // 31: argument (DOUBLE) ->  DOUBLE NAME
     {291, 1}, // 32: declaration_statement_list ->  declaration_statement
     {291, 2}, // 33: declaration_statement_list ->  declaration_statement_list declaration_statement
     {292, 2}, // 34: basic_block_list ->  basic_block_list basic_block
     {292, 1}, // 35: basic_block_list ->  basic_block
     {298, 3}, // 36: basic_block (BASIC_BLOCK) ->  BASIC_BLOCK ':' executable_statement_list
     {299, 1}, // 37: executable_statement_list ->  assignment_statement_list
     {299, 4}, // 38: executable_statement_list (RETURN) ->  assignment_statement_list RETURN return_value ';'
     {299, 2}, // 39: executable_statement_list ->  assignment_statement_list if_else_statement
     {299, 2}, // 40: executable_statement_list ->  assignment_statement_list goto_statement
     {300, 0}, // 41: assignment_statement_list ->  <empty>
     {300, 2}, // 42: assignment_statement_list ->  assignment_statement_list assignment_statement_or_function_call
     {304, 1}, // 43: assignment_statement_or_function_call ->  assignment_statement
     {304, 2}, // 44: assignment_statement_or_function_call (';') ->  function_call ';'
     {305, 4}, // 45: assignment_statement (ASSIGN_OP) ->  variable ASSIGN_OP and_expression ';'
     {302, 7}, // 46: if_else_statement (IF) ->  IF '(' relational_expression ')' goto_statement ELSE goto_statement
     {303, 3}, // 47: goto_statement (GOTO) ->  GOTO BASIC_BLOCK ';'
     {301, 1}, // 48: return_value ->  and_expression
     {301, 0}, // 49: return_value ->  <empty>
     {310, 1}, // 50: not_expression ->  arithmetic_expression
     {310, 1}, // 51: not_expression ->  relational_expression
     {310, 2}, // 52: not_expression (nt) ->  nt relational_expression
     {312, 1}, // 53: or_expression ->  not_expression
     {312, 3}, // 54: or_expression (orTok) ->  not_expression orTok or_expression
     {308, 1}, // 55: and_expression ->  or_expression
     {308, 3}, // 56: and_expression (andTok) ->  or_expression andTok and_expression
     {309, 3}, // 57: relational_expression (eq) ->  relational_expression eq arithmetic_expression
     {309, 3}, // 58: relational_expression (ne) ->  relational_expression ne arithmetic_expression
     {309, 3}, // 59: relational_expression (le) ->  relational_expression le arithmetic_expression
     {309, 3}, // 60: relational_expression (ge) ->  relational_expression ge arithmetic_expression
     {309, 3}, // 61: relational_expression (lt) ->  relational_expression lt arithmetic_expression
     {309, 3}, // 62: relational_expression (gt) ->  relational_expression gt arithmetic_expression
     {309, 3}, // 63: relational_expression (le) ->  arithmetic_expression le arithmetic_expression
     {309, 3}, // 64: relational_expression (ge) ->  arithmetic_expression ge arithmetic_expression
     {309, 3}, // 65: relational_expression (gt) ->  arithmetic_expression gt arithmetic_expression
     {309, 3}, // 66: relational_expression (lt) ->  arithmetic_expression lt arithmetic_expression
     {309, 3}, // 67: relational_expression (eq) ->  arithmetic_expression eq arithmetic_expression
     {309, 3}, // 68: relational_expression (ne) ->  arithmetic_expression ne arithmetic_expression
     {311, 2}, // 69: arithmetic_expression (SUB_OP) ->  SUB_OP variable_or_constant_typecast
     {311, 3}, // 70: arithmetic_expression (ADD_OP) ->  arithmetic_expression ADD_OP arithmetic_expression
     {311, 3}, // 71: arithmetic_expression (SUB_OP) ->  arithmetic_expression SUB_OP arithmetic_expression
     {311, 3}, // 72: arithmetic_expression (MULT_OP) ->  arithmetic_expression MULT_OP arithmetic_expression
     {311, 3}, // 73: arithmetic_expression (DIV_OP) ->  arithmetic_expression DIV_OP arithmetic_expression
     {311, 1}, // 74: arithmetic_expression ->  variable_or_constant_typecast
     {313, 4}, // 75: variable_or_constant_typecast ('(') ->  '(' FLOAT ')' variable_or_constant
     {313, 4}, // 76: variable_or_constant_typecast ('(') ->  '(' DOUBLE ')' variable_or_constant
     {313, 4}, // 77: variable_or_constant_typecast ('(') ->  '(' INTEGER ')' variable_or_constant
     {313, 1}, // 78: variable_or_constant_typecast ->  variable_or_constant
     {306, 4}, // 79: function_call (NAME) ->  NAME '(' argument_input_list ')'
     {306, 3}, // 80: function_call (NAME) ->  NAME '(' ')'
     {315, 3}, // 81: argument_input_list (',') ->  argument_input_list ',' not_expression
     {315, 1}, // 82: argument_input_list ->  not_expression
     {314, 1}, // 83: variable_or_constant ->  variable
     {314, 1}, // 84: variable_or_constant ->  constant
     {314, 1}, // 85: variable_or_constant ->  function_call
     {314, 3}, // 86: variable_or_constant ('(') ->  '(' arithmetic_expression ')'
     {314, 3}, // 87: variable_or_constant ('(') ->  '(' relational_expression ')'
     {307, 1}, // 88: variable (NAME) ->  NAME
     {316, 1}, // 89: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {316, 1}, // 90: constant (FLOAT_NUMBER) ->  FLOAT_NUMBER
     {317, 1}, // 91: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 13} },                                     
    { {       283}, {  1} }, // program                          
    { {       284}, {  2} }, // global_declaration_statement_list
    { {       285}, {  3} }, // procedure_list                   
    { {       294}, {  4} }, // gloabal_declaration_statement    
    { {       286}, {  5} }, // procedure_name                   
    { {       295}, {  6} }, // declaration_statement            
    { {       296}, {  7} }, // function_declaration_statement   
    { {       260}, {  8} }, // NAME                             
    { {       262}, {  9} }, // INTEGER                          
    { {       267}, { 10} }, // FLOAT                            
    { {       268}, { 11} }, // DOUBLE                           
    { {       269}, { 12} }, // VOID                             
    { {         0}, {  0} },                                     
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 11} },                                  
    { {       285}, { 13} }, // procedure_list                
    { {       294}, { 14} }, // gloabal_declaration_statement 
    { {       286}, {  5} }, // procedure_name                
    { {       295}, {  6} }, // declaration_statement         
    { {       296}, {  7} }, // function_declaration_statement
    { {       260}, {  8} }, // NAME                          
    { {       262}, {  9} }, // INTEGER                       
    { {       267}, { 10} }, // FLOAT                         
    { {       268}, { 11} }, // DOUBLE                        
    { {       269}, { 12} }, // VOID                          
    { {         0}, {  0} },                                  
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  3} },                  
    { {     286}, { 15} }, // procedure_name
    { {     260}, {  8} }, // NAME          
    { {       0}, { -2} },                  
};

SR__ s_4[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  2} },         
    { {     289}, { 16} }, // #0002
    { {       0}, { -6} },         
};

SR__ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 17} }, // '('
    { {         0}, {  0} },       
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 18} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 19} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 20} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 21} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_13[] =
{
    { { REQ_DEF}, {  3} },                  
    { {     286}, { 15} }, // procedure_name
    { {     260}, {  8} }, // NAME          
    { {       0}, { -1} },                  
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {  2} },         
    { {     288}, { 22} }, // #0001
    { {       0}, { -4} },         
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       287}, { 23} }, // procedure_body
    { {       123}, { 24} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  7} },                 
    { {       290}, { 25} }, // argument_list
    { {        41}, { 26} }, // ')'          
    { {       297}, { 27} }, // argument     
    { {       262}, { 28} }, // INTEGER      
    { {       267}, { 29} }, // FLOAT        
    { {       268}, { 30} }, // DOUBLE       
    { {         0}, {  0} },                 
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 31} }, // ';'
    { {        40}, { 32} }, // '('
    { {         0}, {  0} },       
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 33} }, // ';'
    { {        40}, { 34} }, // '('
    { {         0}, {  0} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 35} }, // ';'
    { {        40}, { 36} }, // '('
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 37} }, // '('
    { {         0}, {  0} },       
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       287}, { 38} }, // procedure_body
    { {       123}, { 24} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_23[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  9} },                              
    { {       291}, { 39} }, // declaration_statement_list
    { {       292}, { 40} }, // basic_block_list          
    { {       295}, { 41} }, // declaration_statement     
    { {       298}, { 42} }, // basic_block               
    { {       262}, { 43} }, // INTEGER                   
    { {       267}, { 44} }, // FLOAT                     
    { {       268}, { 45} }, // DOUBLE                    
    { {       259}, { 46} }, // BASIC_BLOCK               
    { {         0}, {  0} },                              
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 47} }, // ')'
    { {        44}, { 48} }, // ','
    { {         0}, {  0} },       
};

SR__ s_26[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 49} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 50} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 51} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  7} },                 
    { {       290}, { 52} }, // argument_list
    { {        41}, { 53} }, // ')'          
    { {       297}, { 27} }, // argument     
    { {       262}, { 28} }, // INTEGER      
    { {       267}, { 29} }, // FLOAT        
    { {       268}, { 30} }, // DOUBLE       
    { {         0}, {  0} },                 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  7} },                 
    { {       290}, { 54} }, // argument_list
    { {        41}, { 55} }, // ')'          
    { {       297}, { 27} }, // argument     
    { {       262}, { 28} }, // INTEGER      
    { {       267}, { 29} }, // FLOAT        
    { {       268}, { 30} }, // DOUBLE       
    { {         0}, {  0} },                 
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  7} },                 
    { {       290}, { 56} }, // argument_list
    { {        41}, { 57} }, // ')'          
    { {       297}, { 27} }, // argument     
    { {       262}, { 28} }, // INTEGER      
    { {       267}, { 29} }, // FLOAT        
    { {       268}, { 30} }, // DOUBLE       
    { {         0}, {  0} },                 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  7} },                 
    { {       290}, { 58} }, // argument_list
    { {        41}, { 59} }, // ')'          
    { {       297}, { 27} }, // argument     
    { {       262}, { 28} }, // INTEGER      
    { {       267}, { 29} }, // FLOAT        
    { {       268}, { 30} }, // DOUBLE       
    { {         0}, {  0} },                 
};

SR__ s_38[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_39[] =
{
    { { REQ_DEF}, {   6} },                         
    { {     293}, {  60} }, // #0003                
    { {     295}, {  61} }, // declaration_statement
    { {     262}, {  43} }, // INTEGER              
    { {     267}, {  44} }, // FLOAT                
    { {     268}, {  45} }, // DOUBLE               
    { {       0}, { -10} },                         
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 62} }, // '}'        
    { {       298}, { 63} }, // basic_block
    { {       259}, { 46} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 64} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 65} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 66} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 67} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_47[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  5} },            
    { {       297}, { 68} }, // argument
    { {       262}, { 28} }, // INTEGER 
    { {       267}, { 29} }, // FLOAT   
    { {       268}, { 30} }, // DOUBLE  
    { {         0}, {  0} },            
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 69} }, // ')'
    { {        44}, { 48} }, // ','
    { {         0}, {  0} },       
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 70} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 71} }, // ')'
    { {        44}, { 48} }, // ','
    { {         0}, {  0} },       
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 72} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 73} }, // ')'
    { {        44}, { 48} }, // ','
    { {         0}, {  0} },       
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 74} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 75} }, // ')'
    { {        44}, { 48} }, // ','
    { {         0}, {  0} },       
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 76} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       292}, { 77} }, // basic_block_list
    { {       298}, { 42} }, // basic_block     
    { {       259}, { 46} }, // BASIC_BLOCK     
    { {         0}, {  0} },                    
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 31} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 33} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 35} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_67[] =
{
    { { DEF_RED}, {   3} },                             
    { {     299}, {  78} }, // executable_statement_list
    { {     300}, {  79} }, // assignment_statement_list
    { {       0}, { -41} },                             
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 80} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 81} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 82} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 83} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 84} }, // '}'        
    { {       298}, { 63} }, // basic_block
    { {       259}, { 46} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_79[] =
{
    { { REQ_DEF}, {  11} },                                         
    { {     261}, {  85} }, // RETURN                               
    { {     302}, {  86} }, // if_else_statement                    
    { {     303}, {  87} }, // goto_statement                       
    { {     304}, {  88} }, // assignment_statement_or_function_call
    { {     263}, {  89} }, // IF                                   
    { {     265}, {  90} }, // GOTO                                 
    { {     305}, {  91} }, // assignment_statement                 
    { {     306}, {  92} }, // function_call                        
    { {     307}, {  93} }, // variable                             
    { {     260}, {  94} }, // NAME                                 
    { {       0}, { -37} },                                         
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_85[] =
{
    { { REQ_DEF}, {  18} },                                 
    { {     301}, {  95} }, // return_value                 
    { {     308}, {  96} }, // and_expression               
    { {     312}, {  97} }, // or_expression                
    { {     310}, {  98} }, // not_expression               
    { {     311}, {  99} }, // arithmetic_expression        
    { {     309}, { 100} }, // relational_expression        
    { {     280}, { 101} }, // nt                           
    { {     277}, { 102} }, // SUB_OP                       
    { {     313}, { 103} }, // variable_or_constant_typecast
    { {      40}, { 104} }, // '('                          
    { {     314}, { 105} }, // variable_or_constant         
    { {     307}, { 106} }, // variable                     
    { {     316}, { 107} }, // constant                     
    { {     306}, { 108} }, // function_call                
    { {     260}, {  94} }, // NAME                         
    { {     257}, { 109} }, // INTEGER_NUMBER               
    { {     258}, { 110} }, // FLOAT_NUMBER                 
    { {       0}, { -49} },                                 
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        40}, { 111} }, // '('
    { {         0}, {   0} },       
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       259}, { 112} }, // BASIC_BLOCK
    { {         0}, {   0} },               
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 113} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       266}, { 114} }, // ASSIGN_OP
    { {         0}, {   0} },             
};

SR__ s_94[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, { 115} }, // '('
    { {       0}, { -88} },       
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 116} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_97[] =
{
    { { REQ_DEF}, {   2} },          
    { {     281}, { 117} }, // andTok
    { {       0}, { -55} },          
};

SR__ s_98[] =
{
    { { REQ_DEF}, {   2} },         
    { {     282}, { 118} }, // orTok
    { {       0}, { -53} },         
};

SR__ s_99[] =
{
    { { REQ_DEF}, {  11} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {     273}, { 123} }, // le     
    { {     275}, { 124} }, // ge     
    { {     274}, { 125} }, // gt     
    { {     272}, { 126} }, // lt     
    { {     271}, { 127} }, // eq     
    { {     270}, { 128} }, // ne     
    { {       0}, { -50} },           
};

SR__ s_100[] =
{
    { { REQ_DEF}, {   7} },      
    { {     271}, { 129} }, // eq
    { {     270}, { 130} }, // ne
    { {     273}, { 131} }, // le
    { {     275}, { 132} }, // ge
    { {     272}, { 133} }, // lt
    { {     274}, { 134} }, // gt
    { {       0}, { -51} },      
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {  13} },                                 
    { {       309}, { 135} }, // relational_expression        
    { {       311}, { 136} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {  10} },                                 
    { {       313}, { 137} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {  16} },                                 
    { {       267}, { 138} }, // FLOAT                        
    { {       268}, { 139} }, // DOUBLE                       
    { {       262}, { 140} }, // INTEGER                      
    { {       311}, { 141} }, // arithmetic_expression        
    { {       309}, { 142} }, // relational_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -78} }, 
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -83} }, 
};

SR__ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -84} }, 
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -85} }, 
};

SR__ s_109[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -89} }, 
};

SR__ s_110[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -90} }, 
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, {  13} },                                 
    { {       309}, { 143} }, // relational_expression        
    { {       311}, { 136} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_112[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 144} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_114[] =
{
    { { REQ_TOKEN}, {  17} },                                 
    { {       308}, { 145} }, // and_expression               
    { {       312}, {  97} }, // or_expression                
    { {       310}, {  98} }, // not_expression               
    { {       311}, {  99} }, // arithmetic_expression        
    { {       309}, { 100} }, // relational_expression        
    { {       280}, { 101} }, // nt                           
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {  17} },                                 
    { {       315}, { 146} }, // argument_input_list          
    { {        41}, { 147} }, // ')'                          
    { {       310}, { 148} }, // not_expression               
    { {       311}, {  99} }, // arithmetic_expression        
    { {       309}, { 100} }, // relational_expression        
    { {       280}, { 101} }, // nt                           
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_117[] =
{
    { { REQ_TOKEN}, {  17} },                                 
    { {       308}, { 149} }, // and_expression               
    { {       312}, {  97} }, // or_expression                
    { {       310}, {  98} }, // not_expression               
    { {       311}, {  99} }, // arithmetic_expression        
    { {       309}, { 100} }, // relational_expression        
    { {       280}, { 101} }, // nt                           
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_118[] =
{
    { { REQ_TOKEN}, {  16} },                                 
    { {       312}, { 150} }, // or_expression                
    { {       310}, {  98} }, // not_expression               
    { {       311}, {  99} }, // arithmetic_expression        
    { {       309}, { 100} }, // relational_expression        
    { {       280}, { 101} }, // nt                           
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 151} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 152} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_121[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 153} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_122[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 154} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_123[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 155} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_124[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 156} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_125[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 157} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_126[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 158} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_127[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 159} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_128[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 160} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_129[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 161} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_130[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 162} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_131[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 163} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 164} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_133[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 165} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {  12} },                                 
    { {       311}, { 166} }, // arithmetic_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_135[] =
{
    { { REQ_DEF}, {   7} },      
    { {     271}, { 129} }, // eq
    { {     270}, { 130} }, // ne
    { {     273}, { 131} }, // le
    { {     275}, { 132} }, // ge
    { {     272}, { 133} }, // lt
    { {     274}, { 134} }, // gt
    { {       0}, { -52} },      
};

SR__ s_136[] =
{
    { { REQ_TOKEN}, {  11} },           
    { {       273}, { 123} }, // le     
    { {       275}, { 124} }, // ge     
    { {       274}, { 125} }, // gt     
    { {       272}, { 126} }, // lt     
    { {       271}, { 127} }, // eq     
    { {       270}, { 128} }, // ne     
    { {       276}, { 119} }, // ADD_OP 
    { {       277}, { 120} }, // SUB_OP 
    { {       278}, { 121} }, // MULT_OP
    { {       279}, { 122} }, // DIV_OP 
    { {         0}, {   0} },           
};

SR__ s_137[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_138[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 167} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_139[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 168} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_140[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 169} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_141[] =
{
    { { REQ_TOKEN}, {  12} },           
    { {        41}, { 170} }, // ')'    
    { {       276}, { 119} }, // ADD_OP 
    { {       277}, { 120} }, // SUB_OP 
    { {       278}, { 121} }, // MULT_OP
    { {       279}, { 122} }, // DIV_OP 
    { {       273}, { 123} }, // le     
    { {       275}, { 124} }, // ge     
    { {       274}, { 125} }, // gt     
    { {       272}, { 126} }, // lt     
    { {       271}, { 127} }, // eq     
    { {       270}, { 128} }, // ne     
    { {         0}, {   0} },           
};

SR__ s_142[] =
{
    { { REQ_TOKEN}, {   8} },       
    { {        41}, { 171} }, // ')'
    { {       271}, { 129} }, // eq 
    { {       270}, { 130} }, // ne 
    { {       273}, { 131} }, // le 
    { {       275}, { 132} }, // ge 
    { {       272}, { 133} }, // lt 
    { {       274}, { 134} }, // gt 
    { {         0}, {   0} },       
};

SR__ s_143[] =
{
    { { REQ_TOKEN}, {   8} },       
    { {        41}, { 172} }, // ')'
    { {       271}, { 129} }, // eq 
    { {       270}, { 130} }, // ne 
    { {       273}, { 131} }, // le 
    { {       275}, { 132} }, // ge 
    { {       272}, { 133} }, // lt 
    { {       274}, { 134} }, // gt 
    { {         0}, {   0} },       
};

SR__ s_144[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_145[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 173} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_146[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        41}, { 174} }, // ')'
    { {        44}, { 175} }, // ','
    { {         0}, {   0} },       
};

SR__ s_147[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -80} }, 
};

SR__ s_148[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -82} }, 
};

SR__ s_149[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_150[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_151[] =
{
    { { REQ_DEF}, {   3} },           
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -70} },           
};

SR__ s_152[] =
{
    { { REQ_DEF}, {   3} },           
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -71} },           
};

SR__ s_153[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_154[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -73} }, 
};

SR__ s_155[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -63} },           
};

SR__ s_156[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -64} },           
};

SR__ s_157[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -65} },           
};

SR__ s_158[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -66} },           
};

SR__ s_159[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -67} },           
};

SR__ s_160[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -68} },           
};

SR__ s_161[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -57} },           
};

SR__ s_162[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -58} },           
};

SR__ s_163[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -59} },           
};

SR__ s_164[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -60} },           
};

SR__ s_165[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -61} },           
};

SR__ s_166[] =
{
    { { REQ_DEF}, {   5} },           
    { {     276}, { 119} }, // ADD_OP 
    { {     277}, { 120} }, // SUB_OP 
    { {     278}, { 121} }, // MULT_OP
    { {     279}, { 122} }, // DIV_OP 
    { {       0}, { -62} },           
};

SR__ s_167[] =
{
    { { REQ_TOKEN}, {   9} },                        
    { {       314}, { 176} }, // variable_or_constant
    { {       307}, { 106} }, // variable            
    { {       316}, { 107} }, // constant            
    { {       306}, { 108} }, // function_call       
    { {        40}, { 177} }, // '('                 
    { {       260}, {  94} }, // NAME                
    { {       257}, { 109} }, // INTEGER_NUMBER      
    { {       258}, { 110} }, // FLOAT_NUMBER        
    { {         0}, {   0} },                        
};

SR__ s_168[] =
{
    { { REQ_TOKEN}, {   9} },                        
    { {       314}, { 178} }, // variable_or_constant
    { {       307}, { 106} }, // variable            
    { {       316}, { 107} }, // constant            
    { {       306}, { 108} }, // function_call       
    { {        40}, { 177} }, // '('                 
    { {       260}, {  94} }, // NAME                
    { {       257}, { 109} }, // INTEGER_NUMBER      
    { {       258}, { 110} }, // FLOAT_NUMBER        
    { {         0}, {   0} },                        
};

SR__ s_169[] =
{
    { { REQ_TOKEN}, {   9} },                        
    { {       314}, { 179} }, // variable_or_constant
    { {       307}, { 106} }, // variable            
    { {       316}, { 107} }, // constant            
    { {       306}, { 108} }, // function_call       
    { {        40}, { 177} }, // '('                 
    { {       260}, {  94} }, // NAME                
    { {       257}, { 109} }, // INTEGER_NUMBER      
    { {       258}, { 110} }, // FLOAT_NUMBER        
    { {         0}, {   0} },                        
};

SR__ s_170[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -86} }, 
};

SR__ s_171[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -87} }, 
};

SR__ s_172[] =
{
    { { REQ_TOKEN}, {   3} },                  
    { {       303}, { 180} }, // goto_statement
    { {       265}, {  90} }, // GOTO          
    { {         0}, {   0} },                  
};

SR__ s_173[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_174[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -79} }, 
};

SR__ s_175[] =
{
    { { REQ_TOKEN}, {  15} },                                 
    { {       310}, { 181} }, // not_expression               
    { {       311}, {  99} }, // arithmetic_expression        
    { {       309}, { 100} }, // relational_expression        
    { {       280}, { 101} }, // nt                           
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_176[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR__ s_177[] =
{
    { { REQ_TOKEN}, {  13} },                                 
    { {       311}, { 141} }, // arithmetic_expression        
    { {       309}, { 142} }, // relational_expression        
    { {       277}, { 102} }, // SUB_OP                       
    { {       313}, { 103} }, // variable_or_constant_typecast
    { {        40}, { 104} }, // '('                          
    { {       314}, { 105} }, // variable_or_constant         
    { {       307}, { 106} }, // variable                     
    { {       316}, { 107} }, // constant                     
    { {       306}, { 108} }, // function_call                
    { {       260}, {  94} }, // NAME                         
    { {       257}, { 109} }, // INTEGER_NUMBER               
    { {       258}, { 110} }, // FLOAT_NUMBER                 
    { {         0}, {   0} },                                 
};

SR__ s_178[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -76} }, 
};

SR__ s_179[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -77} }, 
};

SR__ s_180[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       264}, { 182} }, // ELSE
    { {         0}, {   0} },        
};

SR__ s_181[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -81} }, 
};

SR__ s_182[] =
{
    { { REQ_TOKEN}, {   3} },                  
    { {       303}, { 183} }, // goto_statement
    { {       265}, {  90} }, // GOTO          
    { {         0}, {   0} },                  
};

SR__ s_183[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,  s_154,  s_155,  s_156,  s_157,  s_158,  s_159,
  s_160,  s_161,  s_162,  s_163,  s_164,  s_165,  s_166,  s_167,  s_168,  s_169,
  s_170,  s_171,  s_172,  s_173,  s_174,  s_175,  s_176,  s_177,  s_178,  s_179,
  s_180,  s_181,  s_182,  s_183,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
        {
         
        
         }
        break;

        case 2:
        {
         
         }
        break;

        case 3:
        {
         
        
         }
        break;

        case 4:
        d_val__ = d_vsp__[-1];
        {
         
        
         }
        break;

        case 5:
        {
         
        
         }
        break;

        case 6:
        d_val__ = d_vsp__[0];
        {
         
        
         }
        break;

        case 7:
        {
         
        
         
         }
        break;

        case 8:
        {
         
        
         
         }
        break;

        case 9:
        {
         
         if (return_statement_used_flag == false)
         {
         
        
         }
         
        
         
         
         }
        break;

        case 10:
        d_val__ = d_vsp__[-1];
        {
         
        
         
         
         }
        break;

        case 11:
        {
         
         
         
         
         }
        break;

        case 12:
        {
         }
        break;

        case 13:
        {
         }
        break;

        case 14:
        {
         
        
         }
        break;

        case 15:
        {
         }
        break;

        case 16:
        {
         
        
         }
        break;

        case 17:
        {
         
        
         }
        break;

        case 18:
        {
         
        
         }
        break;

        case 19:
        {
         
         }
        break;

        case 20:
        {
         }
        break;

        case 21:
        {
         }
        break;

        case 22:
        {
         }
        break;

        case 23:
        {
         
         }
        break;

        case 24:
        {
         }
        break;

        case 25:
        {
         }
        break;

        case 26:
        {
         }
        break;

        case 27:
        {
         
         }
        break;

        case 28:
        {
         }
        break;

        case 29:
        {
         }
        break;

        case 30:
        {
         }
        break;

        case 31:
        {
         }
        break;

        case 32:
        {
         
        
         }
        break;

        case 33:
        {
         
         
         
         }
        break;

        case 34:
        {
         
        
         }
        break;

        case 35:
        {
         
        
         }
        break;

        case 36:
        {
         
        
         }
        break;

        case 37:
        {
         
        
         
         
         }
        break;

        case 38:
        {
         
        
         }
        break;

        case 39:
        {
         
         
         }
        break;

        case 40:
        {
         
        
         }
        break;

        case 41:
        {
         
        
         
         }
        break;

        case 42:
        {
         
         
         
         }
        break;

        case 43:
        {
         }
        break;

        case 44:
        {
         }
        break;

        case 45:
        {
         
        
         }
        break;

        case 46:
        {
         
        
         }
        break;

        case 47:
        {
         
        
         
         }
        break;

        case 48:
        {
         }
        break;

        case 49:
        {
         }
        break;

        case 50:
        { 
        
         }
        break;

        case 51:
        {
         
         
        
         
         
         }
        break;

        case 52:
        {
         
         
         
         }
        break;

        case 53:
        { 
         
        
         
         
         }
        break;

        case 54:
        {
         
        
         
         }
        break;

        case 55:
        {
         
        
         }
        break;

        case 56:
        {
         
        
         }
        break;

        case 57:
        {
         
        
         }
        break;

        case 58:
        {
         
        
         }
        break;

        case 59:
        {
         
        
         }
        break;

        case 60:
        {
         
        
         }
        break;

        case 61:
        {
         
        
         }
        break;

        case 62:
        {
         
        
         }
        break;

        case 63:
        { 
         
        
         }
        break;

        case 64:
        {
         
        
         }
        break;

        case 65:
        {
         
        
         }
        break;

        case 66:
        {
         
        
         }
        break;

        case 67:
        {
         
        
         }
        break;

        case 68:
        {
         
        
         }
        break;

        case 69:
        {
         
        
         }
        break;

        case 70:
        {
         
        
         }
        break;

        case 71:
        {
         
        
         }
        break;

        case 72:
        {
         
        
         }
        break;

        case 73:
        {
         
        
         }
        break;

        case 74:
        {
         
        
         }
        break;

        case 75:
        {
         
        
         }
        break;

        case 76:
        {
         
        
         }
        break;

        case 77:
        {
         
        
         }
        break;

        case 78:
        {
         
        
         }
        break;

        case 79:
        {
         
         }
        break;

        case 80:
        {
         }
        break;

        case 81:
        {
         }
        break;

        case 82:
        {
         }
        break;

        case 83:
        {
         
        
         }
        break;

        case 84:
        {
         
        
         }
        break;

        case 85:
        {
         }
        break;

        case 86:
        {
         
        
         }
        break;

        case 87:
        {
         
        
         }
        break;

        case 88:
        {
         
        
         }
        break;

        case 89:
        {
         
        
         }
        break;

        case 90:
        {
         
        
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

