// Generated by Bisonc++ V2.09.03 on Mon, 24 Feb 2014 01:58:08 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {298, 4}, // 1: program ->  declaration_statement_list procedure_name #0001 procedure_body
     {301, 0}, // 2: #0001 ->  <empty>
     {298, 3}, // 3: program ->  procedure_name #0002 procedure_body
     {302, 0}, // 4: #0002 ->  <empty>
     {299, 3}, // 5: procedure_name (NAME) ->  NAME '(' ')'
     {300, 5}, // 6: procedure_body ('{') ->  '{' declaration_statement_list #0003 basic_block_list '}'
     {303, 0}, // 7: #0003 ->  <empty>
     {300, 3}, // 8: procedure_body ('{') ->  '{' basic_block_list '}'
     {304, 1}, // 9: declaration_statement_list ->  declaration_statement
     {304, 2}, // 10: declaration_statement_list ->  declaration_statement_list declaration_statement
     {305, 3}, // 11: declaration_statement (INTEGER) ->  INTEGER NAME ';'
     {305, 3}, // 12: declaration_statement (FLOAT) ->  FLOAT NAME ';'
     {306, 2}, // 13: basic_block_list ->  basic_block_list basic_block
     {306, 1}, // 14: basic_block_list ->  basic_block
     {307, 3}, // 15: basic_block (BASIC_BLOCK) ->  BASIC_BLOCK ':' executable_statement_list
     {308, 1}, // 16: executable_statement_list ->  assignment_statement_list
     {308, 3}, // 17: executable_statement_list (RETURN) ->  assignment_statement_list RETURN ';'
     {308, 2}, // 18: executable_statement_list ->  assignment_statement_list if_else_statement
     {308, 2}, // 19: executable_statement_list ->  assignment_statement_list goto_statement
     {309, 0}, // 20: assignment_statement_list ->  <empty>
     {309, 2}, // 21: assignment_statement_list ->  assignment_statement_list assignment_statement
     {310, 4}, // 22: assignment_statement (ASSIGN_OP) ->  variable ASSIGN_OP and_expression ';'
     {311, 7}, // 23: if_else_statement (IF) ->  IF '(' relational_expression ')' goto_statement ELSE goto_statement
     {312, 3}, // 24: goto_statement (GOTO) ->  GOTO BASIC_BLOCK ';'
     {313, 1}, // 25: not_expression ->  arithmetic_expression
     {313, 1}, // 26: not_expression ->  relational_expression
     {313, 2}, // 27: not_expression (nt) ->  nt relational_expression
     {314, 1}, // 28: or_expression ->  not_expression
     {314, 3}, // 29: or_expression (orTok) ->  not_expression orTok or_expression
     {315, 1}, // 30: and_expression ->  or_expression
     {315, 3}, // 31: and_expression (andTok) ->  or_expression andTok and_expression
     {316, 3}, // 32: relational_expression (le) ->  arithmetic_expression le relational_expression
     {316, 3}, // 33: relational_expression (ge) ->  arithmetic_expression ge relational_expression
     {316, 3}, // 34: relational_expression (lt) ->  arithmetic_expression lt relational_expression
     {316, 3}, // 35: relational_expression (gt) ->  arithmetic_expression gt relational_expression
     {316, 3}, // 36: relational_expression (eq) ->  arithmetic_expression eq relational_expression
     {316, 3}, // 37: relational_expression (ne) ->  arithmetic_expression ne relational_expression
     {316, 3}, // 38: relational_expression (le) ->  arithmetic_expression le arithmetic_expression
     {316, 3}, // 39: relational_expression (ge) ->  arithmetic_expression ge arithmetic_expression
     {316, 3}, // 40: relational_expression (gt) ->  arithmetic_expression gt arithmetic_expression
     {316, 3}, // 41: relational_expression (lt) ->  arithmetic_expression lt arithmetic_expression
     {316, 3}, // 42: relational_expression (eq) ->  arithmetic_expression eq arithmetic_expression
     {316, 3}, // 43: relational_expression (ne) ->  arithmetic_expression ne arithmetic_expression
     {317, 2}, // 44: arithmetic_expression (SUB_OP) ->  SUB_OP variable_or_constant
     {317, 4}, // 45: arithmetic_expression ('(') ->  '(' FLOAT ')' arithmetic_expression
     {317, 4}, // 46: arithmetic_expression ('(') ->  '(' INTEGER ')' arithmetic_expression
     {317, 3}, // 47: arithmetic_expression (ADD_OP) ->  arithmetic_expression ADD_OP variable_or_constant
     {317, 3}, // 48: arithmetic_expression (SUB_OP) ->  arithmetic_expression SUB_OP variable_or_constant
     {317, 3}, // 49: arithmetic_expression (MULT_OP) ->  arithmetic_expression MULT_OP variable_or_constant
     {317, 3}, // 50: arithmetic_expression (DIV_OP) ->  arithmetic_expression DIV_OP variable_or_constant
     {317, 1}, // 51: arithmetic_expression ->  variable_or_constant
     {318, 1}, // 52: variable_or_constant ->  variable
     {318, 1}, // 53: variable_or_constant ->  constant
     {318, 3}, // 54: variable_or_constant ('(') ->  '(' arithmetic_expression ')'
     {318, 3}, // 55: variable_or_constant ('(') ->  '(' relational_expression ')'
     {319, 1}, // 56: variable (NAME) ->  NAME
     {320, 1}, // 57: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {320, 1}, // 58: constant (FLOAT_NUMBER) ->  FLOAT_NUMBER
     {321, 1}, // 59: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 8} },                              
    { {       298}, { 1} }, // program                   
    { {       304}, { 2} }, // declaration_statement_list
    { {       299}, { 3} }, // procedure_name            
    { {       305}, { 4} }, // declaration_statement     
    { {       260}, { 5} }, // NAME                      
    { {       262}, { 6} }, // INTEGER                   
    { {       267}, { 7} }, // FLOAT                     
    { {         0}, { 0} },                              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 6} },                         
    { {       299}, { 8} }, // procedure_name       
    { {       305}, { 9} }, // declaration_statement
    { {       260}, { 5} }, // NAME                 
    { {       262}, { 6} }, // INTEGER              
    { {       267}, { 7} }, // FLOAT                
    { {         0}, { 0} },                         
};

SR__ s_3[] =
{
    { { DEF_RED}, {  2} },         
    { {     302}, { 10} }, // #0002
    { {       0}, { -4} },         
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 11} }, // '('
    { {         0}, {  0} },       
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 12} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 13} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_8[] =
{
    { { DEF_RED}, {  2} },         
    { {     301}, { 14} }, // #0001
    { {       0}, { -2} },         
};

SR__ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       300}, { 15} }, // procedure_body
    { {       123}, { 16} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 17} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 18} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 19} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       300}, { 20} }, // procedure_body
    { {       123}, { 16} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_15[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  8} },                              
    { {       304}, { 21} }, // declaration_statement_list
    { {       306}, { 22} }, // basic_block_list          
    { {       305}, {  4} }, // declaration_statement     
    { {       307}, { 23} }, // basic_block               
    { {       262}, {  6} }, // INTEGER                   
    { {       267}, {  7} }, // FLOAT                     
    { {       259}, { 24} }, // BASIC_BLOCK               
    { {         0}, {  0} },                              
};

SR__ s_17[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_21[] =
{
    { { REQ_DEF}, {  5} },                         
    { {     303}, { 25} }, // #0003                
    { {     305}, {  9} }, // declaration_statement
    { {     262}, {  6} }, // INTEGER              
    { {     267}, {  7} }, // FLOAT                
    { {       0}, { -7} },                         
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 26} }, // '}'        
    { {       307}, { 27} }, // basic_block
    { {       259}, { 24} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 28} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       306}, { 29} }, // basic_block_list
    { {       307}, { 23} }, // basic_block     
    { {       259}, { 24} }, // BASIC_BLOCK     
    { {         0}, {  0} },                    
};

SR__ s_26[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {   3} },                             
    { {     308}, {  30} }, // executable_statement_list
    { {     309}, {  31} }, // assignment_statement_list
    { {       0}, { -20} },                             
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 32} }, // '}'        
    { {       307}, { 27} }, // basic_block
    { {       259}, { 24} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_31[] =
{
    { { REQ_DEF}, {   9} },                        
    { {     261}, {  33} }, // RETURN              
    { {     311}, {  34} }, // if_else_statement   
    { {     312}, {  35} }, // goto_statement      
    { {     310}, {  36} }, // assignment_statement
    { {     263}, {  37} }, // IF                  
    { {     265}, {  38} }, // GOTO                
    { {     319}, {  39} }, // variable            
    { {     260}, {  40} }, // NAME                
    { {       0}, { -16} },                        
};

SR__ s_32[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 41} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 42} }, // '('
    { {         0}, {  0} },       
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       259}, { 43} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       266}, { 44} }, // ASSIGN_OP
    { {         0}, {  0} },             
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, { 11} },                         
    { {       316}, { 45} }, // relational_expression
    { {       317}, { 46} }, // arithmetic_expression
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 54} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 15} },                         
    { {       315}, { 55} }, // and_expression       
    { {       314}, { 56} }, // or_expression        
    { {       313}, { 57} }, // not_expression       
    { {       317}, { 58} }, // arithmetic_expression
    { {       316}, { 59} }, // relational_expression
    { {       278}, { 60} }, // nt                   
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 61} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 11} },           
    { {       275}, { 62} }, // le     
    { {       277}, { 63} }, // ge     
    { {       274}, { 64} }, // lt     
    { {       276}, { 65} }, // gt     
    { {       273}, { 66} }, // eq     
    { {       272}, { 67} }, // ne     
    { {       270}, { 68} }, // ADD_OP 
    { {       271}, { 69} }, // SUB_OP 
    { {       268}, { 70} }, // MULT_OP
    { {       269}, { 71} }, // DIV_OP 
    { {         0}, {  0} },           
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  8} },                        
    { {       318}, { 72} }, // variable_or_constant
    { {       319}, { 50} }, // variable            
    { {       320}, { 51} }, // constant            
    { {        40}, { 73} }, // '('                 
    { {       260}, { 40} }, // NAME                
    { {       257}, { 52} }, // INTEGER_NUMBER      
    { {       258}, { 53} }, // FLOAT_NUMBER        
    { {         0}, {  0} },                        
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, { 13} },                         
    { {       267}, { 74} }, // FLOAT                
    { {       262}, { 75} }, // INTEGER              
    { {       317}, { 76} }, // arithmetic_expression
    { {       316}, { 77} }, // relational_expression
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 78} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_56[] =
{
    { { REQ_DEF}, {   2} },          
    { {     279}, {  79} }, // andTok
    { {       0}, { -30} },          
};

SR__ s_57[] =
{
    { { REQ_DEF}, {   2} },         
    { {     280}, {  80} }, // orTok
    { {       0}, { -28} },         
};

SR__ s_58[] =
{
    { { REQ_DEF}, {  11} },           
    { {     270}, {  68} }, // ADD_OP 
    { {     271}, {  69} }, // SUB_OP 
    { {     268}, {  70} }, // MULT_OP
    { {     269}, {  71} }, // DIV_OP 
    { {     275}, {  62} }, // le     
    { {     277}, {  63} }, // ge     
    { {     274}, {  64} }, // lt     
    { {     276}, {  65} }, // gt     
    { {     273}, {  66} }, // eq     
    { {     272}, {  67} }, // ne     
    { {       0}, { -25} },           
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, { 11} },                         
    { {       316}, { 81} }, // relational_expression
    { {       317}, { 46} }, // arithmetic_expression
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       312}, { 82} }, // goto_statement
    { {       265}, { 38} }, // GOTO          
    { {         0}, {  0} },                  
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 11} },                         
    { {       316}, { 83} }, // relational_expression
    { {       317}, { 84} }, // arithmetic_expression
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 11} },                         
    { {       316}, { 85} }, // relational_expression
    { {       317}, { 86} }, // arithmetic_expression
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, { 11} },                         
    { {       316}, { 87} }, // relational_expression
    { {       317}, { 88} }, // arithmetic_expression
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, { 11} },                         
    { {       316}, { 89} }, // relational_expression
    { {       317}, { 90} }, // arithmetic_expression
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, { 11} },                         
    { {       316}, { 91} }, // relational_expression
    { {       317}, { 92} }, // arithmetic_expression
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, { 11} },                         
    { {       316}, { 93} }, // relational_expression
    { {       317}, { 94} }, // arithmetic_expression
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  8} },                        
    { {       318}, { 95} }, // variable_or_constant
    { {       319}, { 50} }, // variable            
    { {       320}, { 51} }, // constant            
    { {        40}, { 73} }, // '('                 
    { {       260}, { 40} }, // NAME                
    { {       257}, { 52} }, // INTEGER_NUMBER      
    { {       258}, { 53} }, // FLOAT_NUMBER        
    { {         0}, {  0} },                        
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  8} },                        
    { {       318}, { 96} }, // variable_or_constant
    { {       319}, { 50} }, // variable            
    { {       320}, { 51} }, // constant            
    { {        40}, { 73} }, // '('                 
    { {       260}, { 40} }, // NAME                
    { {       257}, { 52} }, // INTEGER_NUMBER      
    { {       258}, { 53} }, // FLOAT_NUMBER        
    { {         0}, {  0} },                        
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  8} },                        
    { {       318}, { 97} }, // variable_or_constant
    { {       319}, { 50} }, // variable            
    { {       320}, { 51} }, // constant            
    { {        40}, { 73} }, // '('                 
    { {       260}, { 40} }, // NAME                
    { {       257}, { 52} }, // INTEGER_NUMBER      
    { {       258}, { 53} }, // FLOAT_NUMBER        
    { {         0}, {  0} },                        
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  8} },                        
    { {       318}, { 98} }, // variable_or_constant
    { {       319}, { 50} }, // variable            
    { {       320}, { 51} }, // constant            
    { {        40}, { 73} }, // '('                 
    { {       260}, { 40} }, // NAME                
    { {       257}, { 52} }, // INTEGER_NUMBER      
    { {       258}, { 53} }, // FLOAT_NUMBER        
    { {         0}, {  0} },                        
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 11} },                         
    { {       317}, { 76} }, // arithmetic_expression
    { {       316}, { 77} }, // relational_expression
    { {       271}, { 47} }, // SUB_OP               
    { {        40}, { 48} }, // '('                  
    { {       318}, { 49} }, // variable_or_constant 
    { {       319}, { 50} }, // variable             
    { {       320}, { 51} }, // constant             
    { {       260}, { 40} }, // NAME                 
    { {       257}, { 52} }, // INTEGER_NUMBER       
    { {       258}, { 53} }, // FLOAT_NUMBER         
    { {         0}, {  0} },                         
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 99} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 100} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  12} },           
    { {        41}, { 101} }, // ')'    
    { {       270}, {  68} }, // ADD_OP 
    { {       271}, {  69} }, // SUB_OP 
    { {       268}, {  70} }, // MULT_OP
    { {       269}, {  71} }, // DIV_OP 
    { {       275}, {  62} }, // le     
    { {       277}, {  63} }, // ge     
    { {       274}, {  64} }, // lt     
    { {       276}, {  65} }, // gt     
    { {       273}, {  66} }, // eq     
    { {       272}, {  67} }, // ne     
    { {         0}, {   0} },           
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 102} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  15} },                         
    { {       315}, { 103} }, // and_expression       
    { {       314}, {  56} }, // or_expression        
    { {       313}, {  57} }, // not_expression       
    { {       317}, {  58} }, // arithmetic_expression
    { {       316}, {  59} }, // relational_expression
    { {       278}, {  60} }, // nt                   
    { {       271}, {  47} }, // SUB_OP               
    { {        40}, {  48} }, // '('                  
    { {       318}, {  49} }, // variable_or_constant 
    { {       319}, {  50} }, // variable             
    { {       320}, {  51} }, // constant             
    { {       260}, {  40} }, // NAME                 
    { {       257}, {  52} }, // INTEGER_NUMBER       
    { {       258}, {  53} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       314}, { 104} }, // or_expression        
    { {       313}, {  57} }, // not_expression       
    { {       317}, {  58} }, // arithmetic_expression
    { {       316}, {  59} }, // relational_expression
    { {       278}, {  60} }, // nt                   
    { {       271}, {  47} }, // SUB_OP               
    { {        40}, {  48} }, // '('                  
    { {       318}, {  49} }, // variable_or_constant 
    { {       319}, {  50} }, // variable             
    { {       320}, {  51} }, // constant             
    { {       260}, {  40} }, // NAME                 
    { {       257}, {  52} }, // INTEGER_NUMBER       
    { {       258}, {  53} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       264}, { 105} }, // ELSE
    { {         0}, {   0} },        
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_84[] =
{
    { { REQ_DEF}, {  11} },           
    { {     275}, {  62} }, // le     
    { {     277}, {  63} }, // ge     
    { {     274}, {  64} }, // lt     
    { {     276}, {  65} }, // gt     
    { {     273}, {  66} }, // eq     
    { {     272}, {  67} }, // ne     
    { {     270}, {  68} }, // ADD_OP 
    { {     271}, {  69} }, // SUB_OP 
    { {     268}, {  70} }, // MULT_OP
    { {     269}, {  71} }, // DIV_OP 
    { {       0}, { -38} },           
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_86[] =
{
    { { REQ_DEF}, {  11} },           
    { {     275}, {  62} }, // le     
    { {     277}, {  63} }, // ge     
    { {     274}, {  64} }, // lt     
    { {     276}, {  65} }, // gt     
    { {     273}, {  66} }, // eq     
    { {     272}, {  67} }, // ne     
    { {     270}, {  68} }, // ADD_OP 
    { {     271}, {  69} }, // SUB_OP 
    { {     268}, {  70} }, // MULT_OP
    { {     269}, {  71} }, // DIV_OP 
    { {       0}, { -39} },           
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_88[] =
{
    { { REQ_DEF}, {  11} },           
    { {     275}, {  62} }, // le     
    { {     277}, {  63} }, // ge     
    { {     274}, {  64} }, // lt     
    { {     276}, {  65} }, // gt     
    { {     273}, {  66} }, // eq     
    { {     272}, {  67} }, // ne     
    { {     270}, {  68} }, // ADD_OP 
    { {     271}, {  69} }, // SUB_OP 
    { {     268}, {  70} }, // MULT_OP
    { {     269}, {  71} }, // DIV_OP 
    { {       0}, { -41} },           
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_90[] =
{
    { { REQ_DEF}, {  11} },           
    { {     275}, {  62} }, // le     
    { {     277}, {  63} }, // ge     
    { {     274}, {  64} }, // lt     
    { {     276}, {  65} }, // gt     
    { {     273}, {  66} }, // eq     
    { {     272}, {  67} }, // ne     
    { {     270}, {  68} }, // ADD_OP 
    { {     271}, {  69} }, // SUB_OP 
    { {     268}, {  70} }, // MULT_OP
    { {     269}, {  71} }, // DIV_OP 
    { {       0}, { -40} },           
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_92[] =
{
    { { REQ_DEF}, {  11} },           
    { {     275}, {  62} }, // le     
    { {     277}, {  63} }, // ge     
    { {     274}, {  64} }, // lt     
    { {     276}, {  65} }, // gt     
    { {     273}, {  66} }, // eq     
    { {     272}, {  67} }, // ne     
    { {     270}, {  68} }, // ADD_OP 
    { {     271}, {  69} }, // SUB_OP 
    { {     268}, {  70} }, // MULT_OP
    { {     269}, {  71} }, // DIV_OP 
    { {       0}, { -42} },           
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_94[] =
{
    { { REQ_DEF}, {  11} },           
    { {     275}, {  62} }, // le     
    { {     277}, {  63} }, // ge     
    { {     274}, {  64} }, // lt     
    { {     276}, {  65} }, // gt     
    { {     273}, {  66} }, // eq     
    { {     272}, {  67} }, // ne     
    { {     270}, {  68} }, // ADD_OP 
    { {     271}, {  69} }, // SUB_OP 
    { {     268}, {  70} }, // MULT_OP
    { {     269}, {  71} }, // DIV_OP 
    { {       0}, { -43} },           
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {  10} },                         
    { {       317}, { 106} }, // arithmetic_expression
    { {       271}, {  47} }, // SUB_OP               
    { {        40}, {  48} }, // '('                  
    { {       318}, {  49} }, // variable_or_constant 
    { {       319}, {  50} }, // variable             
    { {       320}, {  51} }, // constant             
    { {       260}, {  40} }, // NAME                 
    { {       257}, {  52} }, // INTEGER_NUMBER       
    { {       258}, {  53} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {  10} },                         
    { {       317}, { 107} }, // arithmetic_expression
    { {       271}, {  47} }, // SUB_OP               
    { {        40}, {  48} }, // '('                  
    { {       318}, {  49} }, // variable_or_constant 
    { {       319}, {  50} }, // variable             
    { {       320}, {  51} }, // constant             
    { {       260}, {  40} }, // NAME                 
    { {       257}, {  52} }, // INTEGER_NUMBER       
    { {       258}, {  53} }, // FLOAT_NUMBER         
    { {         0}, {   0} },                         
};

SR__ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_104[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_105[] =
{
    { { REQ_TOKEN}, {   3} },                  
    { {       312}, { 108} }, // goto_statement
    { {       265}, {  38} }, // GOTO          
    { {         0}, {   0} },                  
};

SR__ s_106[] =
{
    { { REQ_DEF}, {   5} },           
    { {     270}, {  68} }, // ADD_OP 
    { {     271}, {  69} }, // SUB_OP 
    { {     268}, {  70} }, // MULT_OP
    { {     269}, {  71} }, // DIV_OP 
    { {       0}, { -45} },           
};

SR__ s_107[] =
{
    { { REQ_DEF}, {   5} },           
    { {     270}, {  68} }, // ADD_OP 
    { {     271}, {  69} }, // SUB_OP 
    { {     268}, {  70} }, // MULT_OP
    { {     269}, {  71} }, // DIV_OP 
    { {       0}, { -46} },           
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
        {
         program_object.set_procedure_map(*current_procedure);
         if (d_vsp__[-3].symbol_table)
         d_vsp__[-3].symbol_table->global_list_in_proc_map_check(get_line_number());
         delete d_vsp__[-3].symbol_table;
         }
        break;

        case 2:
        d_val__ = d_vsp__[-1];
        {
         program_object.set_global_table(*d_vsp__[-1].symbol_table);
         return_statement_used_flag = true; 
         }
        break;

        case 3:
        {
         program_object.set_procedure_map(*current_procedure);
         }
        break;

        case 4:
        d_val__ = d_vsp__[0];
        {
         return_statement_used_flag = true; 
         }
        break;

        case 5:
        {
         
         current_procedure = new Procedure(void_data_type, *d_vsp__[-2].string_value); 
         
         }
        break;

        case 6:
        {
         
         if (return_statement_used_flag == false)
         {
         int line = get_line_number();
         report_error("Atleast 1 basic block should have a return statement", line);
         }
         current_procedure->set_basic_block_list(*d_vsp__[-1].basic_block_list);
         delete d_vsp__[-1].basic_block_list;
         
         
         }
        break;

        case 7:
        d_val__ = d_vsp__[-1];
        {
         
         current_procedure->set_local_list(*d_vsp__[0].symbol_table);
         delete d_vsp__[0].symbol_table;
         
         
         }
        break;

        case 8:
        {
         
         if (return_statement_used_flag == false)
         {
         int line = get_line_number();
         report_error("Atleast 1 basic block should have a return statement", line);
         }
         current_procedure->set_basic_block_list(*d_vsp__[-1].basic_block_list);
         delete d_vsp__[-1].basic_block_list;
         
         
         }
        break;

        case 9:
        {
         
         int line = get_line_number();
         program_object.variable_in_proc_map_check(d_vsp__[0].symbol_entry->get_variable_name(), line);
         string var_name = d_vsp__[0].symbol_entry->get_variable_name();
         if (current_procedure && current_procedure->get_proc_name() == var_name)
         {
         int line = get_line_number();
         report_error("Variable name cannot be same as procedure name", line);
         }
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         
         
         }
        break;

        case 10:
        {
         
         
         
         
         int line = get_line_number();
         program_object.variable_in_proc_map_check(d_vsp__[0].symbol_entry->get_variable_name(), line);
         string var_name = d_vsp__[0].symbol_entry->get_variable_name();
         if (current_procedure && current_procedure->get_proc_name() == var_name)
         {
         int line = get_line_number();
         report_error("Variable name cannot be same as procedure name", line);
         }
         if (d_vsp__[-1].symbol_table != NULL)
         {
         if(d_vsp__[-1].symbol_table->variable_in_symbol_list_check(var_name))
         {
         int line = get_line_number();
         report_error("Variable is declared twice", line);
         }
         d_val__.symbol_table = d_vsp__[-1].symbol_table;
         }
         else
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         
         
         }
        break;

        case 11:
        {
         
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[-1].string_value, int_data_type);
         delete d_vsp__[-1].string_value;
         
         
         }
        break;

        case 12:
        {
         d_val__.symbol_entry = new Symbol_Table_Entry(*d_vsp__[-1].string_value, float_data_type);
         delete d_vsp__[-1].string_value;
         }
        break;

        case 13:
        {
         
         if (!d_vsp__[0].basic_block)
         {
         int line = get_line_number();
         report_error("Basic block doesn't exist", line);
         }
         bb_strictly_increasing_order_check(d_val__.basic_block_list, d_vsp__[0].basic_block->get_bb_number());
         d_val__.basic_block_list = d_vsp__[-1].basic_block_list;
         if(d_vsp__[0].basic_block != NULL){
         d_val__.basic_block_list->back()->isSuccessor = 1;
         }
         d_val__.basic_block_list->push_back(d_vsp__[0].basic_block);
         
         
         
         }
        break;

        case 14:
        {
         
         if (!d_vsp__[0].basic_block)
         {
         int line = get_line_number();
         report_error("Basic block doesn't exist", line);
         }
         d_val__.basic_block_list = new list<Basic_Block *>;
         d_val__.basic_block_list->push_back(d_vsp__[0].basic_block);
         
         
         }
        break;

        case 15:
        {
         
         if (d_vsp__[-2].integer_value < 2)
         {
         int line = get_line_number();
         printf("%d \n", d_vsp__[-2].integer_value);
         report_error("Illegal basic block lable", line);
         }
         
         if (d_vsp__[0].ast_list != NULL){
         d_val__.basic_block = new Basic_Block(d_vsp__[-2].integer_value, *d_vsp__[0].ast_list);
         if(d_vsp__[0].ast_list->back()->get_successor() != -1){
         d_val__.basic_block->isSuccessor = 1;
         }
         }
         else
         {
         list<Ast *> * ast_list = new list<Ast *>;
         d_val__.basic_block = new Basic_Block(d_vsp__[-2].integer_value, *ast_list);
         }
         delete d_vsp__[0].ast_list; 
         
         }
        break;

        case 16:
        {
         
         d_val__.ast_list = d_vsp__[0].ast_list;
         
         
         }
        break;

        case 17:
        {
         
         Ast * ret = new Return_Ast();
         return_statement_used_flag = true; 
         if (d_vsp__[-2].ast_list != NULL)
         d_val__.ast_list = d_vsp__[-2].ast_list;
         else
         d_val__.ast_list = new list<Ast *>;
         d_val__.ast_list->push_back(ret);
         
         
         }
        break;

        case 18:
        {
         
         if (d_vsp__[-1].ast_list != NULL)
         d_val__.ast_list = d_vsp__[-1].ast_list;
         else
         d_val__.ast_list = new list<Ast *>;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         
         }
        break;

        case 19:
        {
         
         if (d_vsp__[-1].ast_list != NULL)
         d_val__.ast_list = d_vsp__[-1].ast_list;
         else
         d_val__.ast_list = new list<Ast *>;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         
         }
        break;

        case 20:
        {
         
         d_val__.ast_list = NULL;
         
         
         }
        break;

        case 21:
        {
         
         if (d_vsp__[-1].ast_list == NULL)
         d_val__.ast_list = new list<Ast *>;
         else
         d_val__.ast_list = d_vsp__[-1].ast_list;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         
         
         }
        break;

        case 22:
        {
         
         d_val__.ast = new Assignment_Ast(d_vsp__[-3].ast, d_vsp__[-1].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         
         
         }
        break;

        case 23:
        {
         
         d_val__.ast = new If_Else_Ast(d_vsp__[-2].ast, d_vsp__[-4].ast, d_vsp__[0].ast);
         
         
         }
        break;

        case 24:
        {
         if (d_vsp__[-1].integer_value < 2)
         {
         int line = get_line_number();
         
         }
         
         d_val__.ast = new Goto_Ast(d_vsp__[-1].integer_value);
         
         
         }
        break;

        case 25:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 26:
        {
         
         d_val__.ast = d_vsp__[0].ast;
         
         
         }
        break;

        case 27:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[0].ast, NOT, NULL);
         
         
         }
        break;

        case 28:
        { 
         
         d_val__.ast = d_vsp__[0].ast;
         
         
         }
        break;

        case 29:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, OR, d_vsp__[0].ast);
         
         
         }
        break;

        case 30:
        {
         
         d_val__.ast = d_vsp__[0].ast;
         
         
         }
        break;

        case 31:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, AND, d_vsp__[0].ast);
         
         
         }
        break;

        case 32:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, LE, d_vsp__[0].ast);
         
         
         }
        break;

        case 33:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, GE, d_vsp__[0].ast);
         
         
         }
        break;

        case 34:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, LT, d_vsp__[0].ast);
         
         
         }
        break;

        case 35:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, GT, d_vsp__[0].ast);
         
         
         }
        break;

        case 36:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, EQ, d_vsp__[0].ast);
         
         
         }
        break;

        case 37:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, NE, d_vsp__[0].ast);
         
         
         }
        break;

        case 38:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, NE, d_vsp__[0].ast);
         
         
         }
        break;

        case 39:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, NE, d_vsp__[0].ast);
         
         
         }
        break;

        case 40:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, NE, d_vsp__[0].ast);
         
         
         }
        break;

        case 41:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, NE, d_vsp__[0].ast);
         
         
         }
        break;

        case 42:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, NE, d_vsp__[0].ast);
         
         
         }
        break;

        case 43:
        {
         
         d_val__.ast = new Relational_Expr_Ast(d_vsp__[-2].ast, NE, d_vsp__[0].ast);
         
         
         }
        break;

        case 44:
        {
         d_val__.ast = new Arithmetic_Expr_Ast(d_vsp__[0].ast, UMINUS, NULL);
         }
        break;

        case 45:
        {
         d_val__.ast = new Arithmetic_Expr_Ast(d_vsp__[0].ast, F_NUM, NULL);
         }
        break;

        case 46:
        {
         d_val__.ast = new Arithmetic_Expr_Ast(d_vsp__[0].ast, I_NUM, NULL);
         }
        break;

        case 47:
        {
         d_val__.ast = new Arithmetic_Expr_Ast(d_vsp__[-2].ast, PLUS, d_vsp__[0].ast);
         }
        break;

        case 48:
        {
         d_val__.ast = new Arithmetic_Expr_Ast(d_vsp__[-2].ast, MINUS, d_vsp__[0].ast);
         }
        break;

        case 49:
        {
         d_val__.ast = new Arithmetic_Expr_Ast(d_vsp__[-2].ast, MULT, d_vsp__[0].ast);
         }
        break;

        case 50:
        {
         d_val__.ast = new Arithmetic_Expr_Ast(d_vsp__[-2].ast, DIV, d_vsp__[0].ast);
         }
        break;

        case 51:
        {
         d_val__.ast = new Arithmetic_Expr_Ast(d_vsp__[0].ast, VAR, NULL);
         }
        break;

        case 52:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 53:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 54:
        {
         d_val__.ast = d_vsp__[-1].ast;
         }
        break;

        case 55:
        {
         d_val__.ast = d_vsp__[-1].ast;
         }
        break;

        case 56:
        {
         
         Symbol_Table_Entry var_table_entry;
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value);
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = program_object.get_symbol_table_entry(*d_vsp__[0].string_value);
         else
         {
         int line = get_line_number();
         report_error("Variable has not been declared", line);
         }
         d_val__.ast = new Name_Ast(*d_vsp__[0].string_value, var_table_entry);
         delete d_vsp__[0].string_value;
         
         
         }
        break;

        case 57:
        {
         
         d_val__.ast = new Number_Ast<int>(d_vsp__[0].integer_value, int_data_type);
         
         
         }
        break;

        case 58:
        {
         d_val__.ast = new Number_Ast<float>(d_vsp__[0].float_value, float_data_type);
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

