#!/bin/bash
./cfglp -ast test_files/Arith.cs306.cfg
./cfglp -ast test_files/ArithBrckt.cs306.cfg
./cfglp -ast test_files/ArithFloat.cs306.cfg
./cfglp -ast test_files/ArithIntFloat.cs306.cfg
./cfglp -ast test_files/Brckt.cs306.cfg
./cfglp -ast test_files/Const.cs306.cfg
./cfglp -ast test_files/EmptyIf.cs306.cfg
./cfglp -ast test_files/FloatRelArith.cs306.cfg
./cfglp -ast test_files/FloatUnary.cs306.cfg
./cfglp -ast test_files/Glob.cs306.cfg
./cfglp -ast test_files/GlobRemov.cs306.cfg
./cfglp -ast test_files/IfArith.cs306.cfg
./cfglp -ast test_files/IfFloatArith.cs306.cfg
./cfglp -ast test_files/IfFloatRelArith.cs306.cfg
./cfglp -ast test_files/IfIntFloat.cs306.cfg
./cfglp -ast test_files/IfIntFloatRelArith.cs306.cfg
./cfglp -ast test_files/IfRelArith.cs306.cfg
./cfglp -ast test_files/IfUnary.cs306.cfg
./cfglp -ast test_files/IntInFloat.cs306.cfg
./cfglp -ast test_files/RelArith.cs306.cfg
./cfglp -ast test_files/RelArithBrckt.cs306.cfg
./cfglp -ast test_files/RetInFor.cs306.cfg
./cfglp -ast test_files/TypeCast.cs306.cfg
./cfglp -ast test_files/Unary.cs306.cfg
./cfglp -ast test_files/UnaryPlus.cs306.cfg
./cfglp -ast test_files/UserIfTmp.cs306.cfg
./cfglp -ast test_files/test.cs306.cfg
./cfglp -tokens test_files/test.cs306.cfg